apiVersion: v1
kind: ConfigMap
metadata:
  name: failure-playground-config
data:
  ENVIRONMENT: kubernetes-local
  DATABASE_URL: postgresql+psycopg2://app:app@postgres-service:5432/failure_playground
  REDIS_HOST: redis-service
  REDIS_PORT: "6379"
  API_BASE_URL: http://api-service:8000
  OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger-service:4317
  POSTGRES_USER: app
  POSTGRES_PASSWORD: app
  POSTGRES_DB: failure_playground
  PGDATA: /var/lib/postgresql/data/pgdata
